openapi: "3.0.0"
info:
  title: Cart

  version: "1.0.0"
# security:
#      - JWT: []
servers:
  - url: http://localhost:8004
paths:
  /cart:
   post:
      tags:
        - Cart
      summary: create Cart
      description: create new Cart 
      parameters:
        - name: 'Authorization'
          in: header
          required: true
          description: JWT token
          schema:
            type: string
            format: string
            example: a2f6b8d7-8e5c-4023-913f-6f81d4ca92b0
      requestBody:
        description: Request to create new Cart
        content:
          application/form-data:
            schema:
              $ref: '#/components/schemas/cartRequestBody'
        required: true
      responses:
        '200':
          description: successfully created orde
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cartResponseBody'
        
        '404':
          description: 'Not Found: This response is shown if the request for information is not there or it could not be imported'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
   get:
      summary: Get all cart
      description: Get an existing test
      parameters:
        - name: 'Authorization'
          in: header
          required: true
          description: JWT token
          schema:
            type: string
            format: string
            example: a2f6b8d7-8e5c-4023-913f-6f81d4ca92b0
      tags:
        - Cart
      # parameters:
      #   - name: 'advisorId'
      #     in: path
      #     required: true
      #     description: The UUID of advisor
      #     example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      #     schema:
      #       type: string
      #       format: uuid
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cartResponseBody'
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided postId is not valid
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Post not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /cart/{CartId}:
   get:
      summary: Get particular Cart 
      description: Get single Cart
      parameters:
        - name: 'CartId'
          in: path
          required: true
          description: The UUID of the Cart
          schema:
            type: string
            format: string
            example: a2f6b8d7-8e5c-4023-913f-6f81d4ca92b0

        - name: 'Authorization'
          in: header
          required: true
          description: JWT token
          schema:
            type: string
            format: string
            example: a2f6b8d7-8e5c-4023-913f-6f81d4ca92b0
      tags:
        - Cart
      # parameters:
      #   - name: 'advisorId'
      #     in: path
      #     required: true
      #     description: The UUID of advisor
      #     example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      #     schema:
      #       type: string
      #       format: uuid
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cartSchema'
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided CartId is not valid
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Post not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
   patch:
      tags:
        - Cart
      parameters:
        - name: 'CartId'
          in: path
          required: true
          description: The UUID of Cart
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
          schema:
            type: string
            format: uuid
        - name: 'Authorization'
          in: header
          required: true
          description: JWT token
          schema:
            type: string
            format: string
            example: a2f6b8d7-8e5c-4023-913f-6f81d4ca92b0
      summary: update the existing Cart
      description: update the existing Cart
      responses:
        '200':
          description: Cart updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Cart updated successfully.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Cart not found
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided CartId is not valid, 1234
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
 
   delete:
      tags:
        - Cart
      parameters:
        - name: 'CartId'
          in: path
          required: true
          description: The UUID of Cart
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
          schema:
            type: string
            format: uuid

        - name: 'Authorization'
          in: header
          required: true
          description: JWT token
          schema:
            type: string
            format: string
            example: a2f6b8d7-8e5c-4023-913f-6f81d4ca92b0
      summary: Delete the Cart
      description: Deletes the Cart and set the status to inactive. Returns a message after deleting the post
      requestBody:
        description: Request to delete Cart
        content:
          application/json:
            schema:
              type: object
              properties:
                deletedBy:
                  type: string
                  example: user@zenmonk.tech    
        required: true
      responses:
        '200':
          description: Cart deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Cart deleted successfully.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Cart not found
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided CartId is not valid.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
  
  


components:
  schemas:
    cartSchema:
      type: object
      properties:
        _id:
          type: string
          format: uuid
        userid:
          type: string    
        shipping_address:
          type: string
        products:
          type: array
          items:
           type: string
            

        bill:
          type: number
        createdBy:
          type: string
        createdAt:
          type: string
          format: date-time
          description: Creation date and time
          example: "2023-07-25T08:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Updation date and time
          example: "2023-07-25T08:30:00Z"     

    cartResponseBody:
      type: object
      properties:
        userid:
          type: string    
        productId:
           type: array
           items: 
             type: string
        createdAt:
          type: string
          description: The created date
          format: date-time
        updatedAt:
          type: string
          description: updated date
          format: date-time

    cartRequestBody:
      type: object
      properties:
        userid:
          type: string       
        products:
          type: array
          items:
           type: string
       

